### ISSUE TITLE
Convert this normal html css js project to ReactJS

### ISSUE THREAD

**Issue by kartikvirendrar** [kartikvirendrar/stocksearch#8]

**Comment by sakshi135** [comment]
I want to contribute in this. please assign me this.

**Comment by pscon** [comment]
i want to contribute. please assign me

**Comment by atharva-gadekar** [comment]
I want to contribute to this issue after I complete the first issue. Please assign this issue to me.

**Comment by SahilSingh177** [comment]
I want to contribute. Please assign this to me.

**Comment by gaurav-iitb** [comment]
I want to contribute please assign it to me
